### ISSUE TITLE
License missing

### ISSUE THREAD

**Issue by ignoramous** [yigitkonur/swift-ocr-llm-powered-pdf-to-markdown#1]
Probably a MIT or BSD might do.

**Comment by yigitkonur** [comment]
Thanks for the heads up. The free version should work fine for everyone. I didn't really do anything special, so let's not blow it out of proportion https://github.com/yigitkonur/swift-ocr-llm-powered-pdf-to-markdown/commit/bdd99cfdad7a6f9b4586899b47a09717f9f58a46
